### ISSUE TITLE
Icons Needed

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot-Mobile#131]
@nicolasmroberts We need icons for Pet, Other Features, Fabrics, Sed Strat Section and Sed Interval.

Also note you have `SedStructure_pressed` & `SedStructure_pressed_1` instead of simpley`SedStructure`.

Even though we don't have pages for these yet I'm using the buttons in the Spot List to show the info that has been filled out, as is in SS1 and @panamint55 requested, in downloaded project. See #121

**Comment by jessicagood** [comment]
@nicolasmroberts Still missing icons for the following - mostly just the transparent icon

other_features
pet
fabrics
strat_section
sed interval
sed lithologies
sed bedding
sed structures
sed diagenesis
sed fossils
sed interpretations

**Comment by nicolasmroberts** [comment]
@jessicagood Here are the new icons you asked for, including a Button, Button_pressed, _pressed, and _transparent version of each.
[StraboIcons_v7.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/5241855/StraboIcons_v7.zip)

**Comment by jessicagood** [comment]
@nicolasmroberts 
- Can you name `LineButton_pressed copy` something like `LineFreehandButton_pressed` instead? And the associated files.
- There are also a lot of `PolygonFreehandButton copy` files where the icon looks like the strat column. These could be removed.
- You added some `Artboard` files which I don't think we need either.
- I see you added `Sed` to the beginning of the file names for sed icons but it looks like you still have `Bedding`, `Lithologies_pressed`, `Fossil`, and `Diagenesis` files which can now be removed.
- `SedInterpretation_1`, `SedStructure_1`: Shouldn't they not have the `_1`?

I want to get to the point where I can just drop in your icon zip files if icons are changed or added so that's why we need the changes made in your master file, not just in ours.

**Comment by jessicagood** [comment]
@nicolasmroberts Can I also get an icon that will go in the Notebook panel footer which will pop up a list of additional pages? Thanks.

**Comment by nicolasmroberts** [comment]
@jessicagood new set of icons with all the comments you had above. 

Changes to name: 

Freehand line symbol is now called “LineFreehandButton” and “LineFreehandButton_pressed”
Strat spot symbols are called “StratPolygon_pressed”, “StratLine_pressed”,”StratPoint_pressed” “StratLayer_pressed”
"OtherFeature" family of symbols is now called "MoreTools" -- this is the symbol in the notebook page to access the other tools not in the notebook toolbar. There is currently no symbol anymore for "OtherFeature". Working on that.
"VelumButton" has been completely redrawn in anticipation of that feature.

[StraboIcons_v8.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/5348942/StraboIcons_v8.zip)

**Comment by jessicagood** [comment]
@nicolasmroberts Ok, don't think I saw this. Will check out it out. There is a close button but still need a button to open the spot in the notebook page from the image gallery slideshow. Or maybe this should just be the notebook icon?

**Comment by jessicagood** [comment]
In v8 icons all of the Buttons have a white background instead of transparent. I think we need it transparent.

**Comment by nicolasmroberts** [comment]
That's an export error on my part from illustrator. And RE: #78, they are in there -- they are called "StratPoint_pressed", "StratLine_pressed", "StratPolygon_pressed"
![StratLayer_pressed@3x](https://user-images.githubusercontent.com/35352527/97599450-03a87700-19d6-11eb-8e18-2daa58126e0f.png)
![StratLine_pressed@3x](https://user-images.githubusercontent.com/35352527/97599452-04410d80-19d6-11eb-99e9-f79ad2b30738.png)
![StratPoint_pressed@3x](https://user-images.githubusercontent.com/35352527/97599453-04d9a400-19d6-11eb-850c-ab824642de14.png)
![StratPolygon_pressed@3x](https://user-images.githubusercontent.com/35352527/97599454-04d9a400-19d6-11eb-94be-5e68c6a3e27f.png)




[StraboIconV8_Transparent.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/5459686/StraboIconV8_Transparent.zip)

**Comment by nicolasmroberts** [comment]
@jessicagood the .zip folder attached above should fix the issue

**Comment by jessicagood** [comment]
@nicolasmroberts Ok, great! And what about point, lines and polys mapped on an image baseamps (also from #78)? I had separate icons for them too in SS1. Do you want those in SS2? And are they already in the icon zip as well?

**Comment by nicolasmroberts** [comment]
@jessicagood ah right. Here is a new version with those included: "ImageLine_pressed", "imagePoint_pressed", etc. 
[StraboIcons_v8_transperant2.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/5460086/StraboIcons_v8_transperant2.zip)
![ImageLine_pressed@3x](https://user-images.githubusercontent.com/35352527/97607546-225f3b80-19df-11eb-83cd-4ce00fc8e00e.png)
![ImagePoint_pressed@3x](https://user-images.githubusercontent.com/35352527/97607547-22f7d200-19df-11eb-9be2-454c34c09c38.png)
![ImagePolygon_pressed@3x](https://user-images.githubusercontent.com/35352527/97607550-22f7d200-19df-11eb-9358-7dfae74e40a7.png)

**Comment by jessicagood** [comment]
@nicolasmroberts I added these with commit 3bc912a but still see the following problems:

- Missing icons for Other Features
- Missing icons for Sed Interval 
- layersButton starts with a lowercase where as the rest start with a capital
- SedBeding_pressed misspelled
- SedStrabColumn misspelled

**Comment by nicolasmroberts** [comment]
[StraboIcons_v8.2.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/5512055/StraboIcons_v8.2.zip)


Here are corrections:

- all spelling listed was corrected
- StratLayer family of buttons was changed to 'SedInterval' to better fit the naming scheme
- OtherFeatures family of buttons was added.

**Comment by jessicagood** [comment]
@nicolasmroberts Artboard snuck back in there but I just deleted those files so no need a for new version at this point. Looking good so closing this issue.
